version: '3'
services: 
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins2
        ports: 
        - "8880:8080"
        - "50000:50000"
        volumes: 
        - ../volumes/jenkins:/var/jenkins_home
        networks: 
        - docker_network
    ubuntu_slave:
        container_name: ubuntu2
        volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        build:
          context: ../dockerfiles/slave/
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Slave/jenkins-agent.jnlp -secret 2c657eb4b51021cd1f5578a735934c209af21a6ccaa08931e3cbc5467830b32e -workDir "/home/"
        depends_on:
        - jenkins
        networks: 
        - docker_network
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss
        container_name: artifactorycompose
        volumes: 
        - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports: 
        - "8081:8081"
        - "8082:8082"
        networks: 
        - docker_network           
    selenium_hub:
        image: selenium/hub
        container_name: seleniumhubcompose
        networks: 
        - docker_network
        ports: 
        - "4444:4444"        
    selenium_firefox:
        image: selenium/node-firefox
        container_name: seleniumnodefirefoxcompose
        networks: 
            - docker_network
        environment: 
        - HUB_HOST=seleniumhubcompose
        - HUB_PORT=4444
        depends_on: 
        - selenium_hub               
networks: 
    docker_network:
        driver: bridge 